from collections import OrderedDict

en_de = OrderedDict(
    {
        "Hello.": "Hallo.",
        "Hi!": "Hallo!",
        "Good morning.": "Guten Morgen.",
        "Good afternoon.": "Guten Tag.",
        "Good evening.": "Guten Abend.",
        "Goodnight.": "Gute Nacht.",
        "See you soon.": "Bis bald.",
        "See you tomorrow.": "Bis morgen.",
        "See you on Saturday.": "Wir sehen uns am Samstag.",
        "Bye!": "Tschüss!",
        "No.": "NEIN.",
        "I don’t know.": "Ich weiß nicht.",
        "Please.": "Bitte.",
        "I don’t understand.": "Ich verstehe nicht.",
        "Thank you.": "Danke schön.",
        "No, thanks.": "Nein danke.",
        "Excuse me.": "Verzeihung.",
        "Sorry?": "Entschuldigung?",
        "I’m sorry.": "Es tut mir Leid.",
        "OK!": "OK!",
        "You’re welcome.": "Gern geschehen.",
        "How old are you?": "Wie alt bist du?",
        "May I ask how old you are?": "Darf ich fragen wie alt du bist?",
        "When is your birthday?": "Wann ist dein Geburtstag?",
        "I’m years old.": "Ich bin Jahre alt.",
        "Where are you from?": "Woher kommst du?",
        "Where do you live?": "Wo wohnst du?",
        "I’m married.": "Ich bin verheiratet.",
        "I have a partner.": "Ich habe einen Partner.",
        "I’m single.": "Ich bin Single.",
        "I’m divorced.": "Ich bin geschieden.",
        "I’m widowed.": "Ich bin verwitwet.",
        "Do you have any children?": "Hast du Kinder?",
        "I have children.": "Ich habe Kinder.",
        "I don’t have any children.": "Ich habe keine Kinder.",
        "How are you?": "Wie geht es dir?",
        "How’s it going?": "Wie geht's?",
        "How are they?": "Wie sind sie?",
        "Very well, thanks, and you?": "Sehr gut, danke und du?",
        "Fine, thanks.": "Danke, gut.",
        "Great!": "Großartig!",
        "So-so.": "Soso.",
        "Not bad, thanks.": "Nicht schlecht, danke.",
        "Could be worse.": "Könnte schlimmer sein.",
        "I’m fine.": "Mir geht es gut.",
        "I’m tired.": "Ich bin müde.",
        "Durst.": "Durst.",
        "Where do you work?": "Wo arbeitest du?",
        "What do you do?": "Was machst du?",
        "What’s your occupation?": "Was ist dein Beruf?",
        "I’m self-employed.": "Ich bin selbstständig.",
        "I’m unemployed.": "Ich bin arbeitslos.",
        "I’m at university.": "Ich bin in der Universität.",
        "I’m retired.": "Ich bin im Ruhestand.",
        "I’m travelling.": "Ich reise.",
        "I work from home.": "Ich arbeite von Zuhause.",
        "It’s nine o’clock.": "Es ist neun Uhr.",
        "It’s ten past nine.": "Es sind zehn nach neun.",
        "It’s quarter past nine.": "Es ist viertel nach neun.",
        "It’s 25 past nine.": "Es ist 25 nach neun.",
        "It’s half past nine.": "Es ist halb zehn.",
        "It’s 20 to ten.": "Es ist 20 bis zehn.",
        "It’s quarter to ten.": "Es ist viertel vor zehn.",
        "It’s five to ten.": "Es ist fünf bis zehn.",
        "It’s 17:30.": "Es ist 17:30.",
        "When?": "Wann?",
        "How’s the weather?": "Wie ist das Wetter?",
        "Is it going to rain?": "Es wird regnen?",
        "What a lovely day!": "Was für ein schöner Tag!",
        "What awful weather!": "Was für ein schreckliches Wetter!",
        "It’s sunny.": "Es ist sonnig.",
        "It’s foggy.": "Es ist neblig.",
        "It’s freezing.": "Es friert.",
        "It’s windy.": "Es ist windig.",
        "It’s stormy.": "Es ist stürmisch.",
        "It’s changeable.": "Es ist veränderlich.",
    }
)

pl_es = OrderedDict(
    {
        "Cześć.": "Hola.",
        "Dzień dobry.": "Buen día.",
        "Dobry wieczór.": "Buenas tardes.",
        "Dobranoc.": "Buenas noches.",
        "Do zobaczenia wkrótce.": "Nos vemos pronto.",
        "Do zobaczenia jutro.": "Nos vemos mañana.",
        "Do zobaczenia w sobotę.": "Nos vemos el Sábado.",
        "Do widzenia!": "¡Adiós!",
        "NIE.": "NO.",
        "Nie wiem.": "No sé.",
        "Proszę.": "Por favor.",
        "Nie rozumiem.": "No entiendo.",
        "Dziękuję.": "Gracias.",
        "Nie, dziękuję.": "No, gracias.",
        "Przepraszam.": "Lo siento.",
        "Przepraszam?": "¿Lo siento?",
        "OK!": "¡Aproximadamente!",
        "Nie ma za co.": "De nada.",
        "Ile masz lat?": "¿Cuántos años tiene?",
        "Czy mogę zapytać, ile masz lat?": "¿Puedo preguntar cuántos años tienes?",
        "Kiedy są twoje urodziny?": "¿Cuándo es tu cumpleaños?",
        "Mam lat.": "Tengo años.",
        "Skąd jesteś?": "¿De dónde eres?",
        "Gdzie mieszkasz?": "¿Dónde vive?",
        "Jestem żonaty.": "Estoy casado.",
        "Mam partnera.": "Yo tengo un compañero.",
        "Jestem singlem.": "Estoy soltero.",
        "Jestem rozwiedziony.": "Estoy divorciado.",
        "Jestem owdowiała.": "Estoy viudo.",
        "Czy masz jakieś dzieci?": "¿Tienes hijos?",
        "Mam dzieci.": "Tengo hijos.",
        "Nie mam żadnych dzieci.": "No tengo hijos.",
        "Jak się masz?": "¿Cómo estás?",
        "Jak leci?": "¿Cómo estás?",
        "Jak się mają?": "¿Cómo son?",
        "Dzięki bardzo dobrze a ty?": "Gracias muy bien y tu?",
        "Dobrze, dzięki.": "Bien gracias.",
        "Świetnie!": "¡Excelente!",
        "Tak sobie.": "No es bueno.",
        "Nieźle, dzięki.": "No esta mal gracias.",
        "Mogło być gorzej.": "Podría ser peor.",
        "Nic mi nie jest.": "Estoy bien.",
        "Jestem zmęczony.": "Estoy cansado.",
        "Durst.": "Durst.",
        "Gdzie pracujesz?": "¿Dónde trabajas?",
        "Co robisz?": "¿Qué estás haciendo?",
        "Czym się zajmujesz?": "¿A qué te dedicas?",
        "Jestem samozatrudniony.": "Soy trabajador por cuenta propia.",
        "Jestem bezrobotny.": "Soy desempleado.",
        "Jestem na uniwersytecie.": "Estoy en la universidad.",
        "Jestem na emeryturze.": "Soy jubilado.",
        "Ja podróżuję.": "Estoy viajando.",
        "Pracuję w domu.": "Trabajo en casa.",
        "Jest dziewiąta.": "Es noveno.",
        "To dziesięć w ciągu dziewięciu.": "Son diez en las nueve.",
        "Jest piętnaście po dziewiątej.": "Son quince después de las nueve.",
        "Jest 25 mini dziewiątych.": "Hay 25 mini nueve.",
        "Jest w pół do dziesiątej.": "Es a la mitad a diez.",
        "To 20 do dziesięciu.": "Son de 20 a diez.",
        "To kwartał do dziesięciu.": "Este es un cuarto a diez.",
        "To pięć do dziesięciu.": "Son de cinco a diez.",
        "Jest 17:30.": "Son las 17:30.",
        "Gdy?": "¿Cuando?",
        "Jaka jest pogoda?": "¿Cuál es el clima?",
        "Będzie padać?": "¿Va a llover?",
        "Co za piękny dzień!": "¡Qué hermoso día!",
        "Jaka okropna pogoda!": "¡Qué mal tiempo!",
        "Jest słonecznie.": "Está soleado.",
        "Jest mgliście.": "Hay niebla.",
        "Jest lodowato.": "Es helado.",
        "Jest wietrznie.": "Hace viento.",
        "Jest burzowo.": "Esta tormentoso.",
        "Jest zmienny.": "Es variable.",
    }
)

pl_en = OrderedDict(
    [('Cześć.', 'Hi.'), ('Dzień dobry.', 'Good morning.'), ('Dobry wieczór.', 'Good evening.'),
     ('Dobranoc.', 'Good night.'), ('Do zobaczenia wkrótce.', 'See you soon.'),
     ('Do zobaczenia jutro.', 'See you tomorrow.'), ('Do zobaczenia w sobotę.', 'See you on Saturday.'),
     ('Do widzenia!', 'Goodbye!'), ('NIE.', 'NO.'),
     ('Nie wiem.', "I don't know."), ('Proszę.', 'Please.'), ('Nie rozumiem.', "I don't understand."),
     ('Dziękuję.', 'Thank you.'), ('Nie, dziękuję.', 'No thanks.'), ('Przepraszam.', 'Sorry.'),
     ('Przepraszam?', 'Sorry?'), ('OK!', 'OK!'), ('Nie ma za co.', "You're welcome."),
     ('Ile masz lat?', 'How old are you?'),
     ('Czy mogę zapytać, ile masz lat?', 'Can I ask how old you are?'),
     ('Kiedy są twoje urodziny?', 'When is your birthday?'), ('Mam lat.', 'I am years old.'),
     ('Skąd jesteś?', 'Where are you from?'), ('Gdzie mieszkasz?', 'Where do you live?'),
     ('Jestem żonaty.', "I'm married."), ('Mam partnera.', 'I have a partner.'),
     ('Jestem singlem.', "I'm single."), ('Jestem rozwiedziony.', "I'm divorced."),
     ('Jestem owdowiała.', 'I am widowed.'), ('Czy masz jakieś dzieci?', 'Do you have any children?'),
     ('Mam dzieci.', 'I have children.'), ('Nie mam żadnych dzieci.', "I don't have any children."),
     ('Jak się masz?', 'How are you?'), ('Jak leci?', 'How are you?'),
     ('Jak się mają?', 'How are they?'), ('Dzięki bardzo dobrze a ty?', 'Thanks very well and you?'),
     ('Dobrze, dzięki.', 'Good thanks.'), ('Świetnie!', 'Great!'), ('Tak sobie.', 'Not great.'),
     ('Nieźle, dzięki.', 'Not bad, thanks.'), ('Mogło być gorzej.', 'It could be worse.'),
     ('Nic mi nie jest.', "I'm fine."), ('Jestem zmęczony.', "I'm tired."), ('Durst.', 'Durst.'),
     ('Gdzie pracujesz?', 'Where do you work?'), ('Co robisz?', 'What are you doing?'),
     ('Czym się zajmujesz?', 'What do you do?'), ('Jestem samozatrudniony.', 'I am self -employed.'),
     ('Jestem bezrobotny.', "I'm unemployed."), ('Jestem na uniwersytecie.', 'I am at the university.'),
     ('Jestem na emeryturze.', 'I am retired.'), ('Ja podróżuję.', 'I am travelling.'),
     ('Pracuję w domu.', 'I work at home.'), ('Jest dziewiąta.', 'It is ninth.'),
     ('To dziesięć w ciągu dziewięciu.', "It's ten in nine."),
     ('Jest piętnaście po dziewiątej.', 'It is fifteen after nine.'),
     ('Jest 25 mini dziewiątych.', 'There is 25 mini nine.'),
     ('Jest w pół do dziesiątej.', 'It is in half to ten.'),
     ('To 20 do dziesięciu.', "It's 20 to ten."),
     ('To kwartał do dziesięciu.', 'This is a quarter to ten.'),
     ('To pięć do dziesięciu.', "It's five to ten."), ('Jest 17:30.', "It's 17:30."), ('Gdy?', 'When?'),
     ('Jaka jest pogoda?', 'What is the weather?'), ('Będzie padać?', "It's going to rain?"),
     ('Co za piękny dzień!', 'What a beautiful day!'),
     ('Jaka okropna pogoda!', 'How terrible weather!'), ('Jest słonecznie.', "It's sunny."),
     ('Jest mgliście.', "It's foggy."), ('Jest lodowato.', 'It is icy.'),
     ('Jest wietrznie.', "It's windy."), ('Jest burzowo.', 'It is stormy.'),
     ('Jest zmienny.', 'Is variable.')]
)

pl_pt = OrderedDict(
    [('Cześć.', 'Oi.'), ('Dzień dobry.', 'Bom dia.'), ('Dobry wieczór.', 'Boa noite.'), ('Dobranoc.', 'Boa noite.'),
     ('Do zobaczenia wkrótce.', 'Vejo você em breve.'), ('Do zobaczenia jutro.', 'Vejo você amanhã.'),
     ('Do zobaczenia w sobotę.', 'Vejo você no sábado.'), ('Do widzenia!', 'Adeus!'),
     ('NIE.', 'NÃO.'), ('Nie wiem.', 'Não sei.'), ('Proszę.', 'Por favor.'), ('Nie rozumiem.', 'Eu não entendo.'),
     ('Dziękuję.', 'Obrigado.'), ('Nie, dziękuję.', 'Não, obrigado.'), ('Przepraszam.', 'Desculpe.'),
     ('Przepraszam?', 'Desculpe?'), ('OK!', 'OK!'), ('Nie ma za co.', 'De nada.'),
     ('Ile masz lat?', 'Quantos anos você tem?'),
     ('Czy mogę zapytać, ile masz lat?', 'Posso perguntar quantos anos você tem?'),
     ('Kiedy są twoje urodziny?', 'Quando é seu aniversário?'), ('Mam lat.', 'Eu tenho anos de idade.'),
     ('Skąd jesteś?', 'De onde você é?'), ('Gdzie mieszkasz?', 'Onde você mora?'), ('Jestem żonaty.', 'Eu sou casado.'),
     ('Mam partnera.', 'Eu tenho um parceiro.'), ('Jestem singlem.', 'Sou solteiro.'),
     ('Jestem rozwiedziony.', 'Eu sou divorciado.'), ('Jestem owdowiała.', 'Eu sou viúvo.'),
     ('Czy masz jakieś dzieci?', 'Você tem filhos?'), ('Mam dzieci.', 'Eu tenho filhos.'),
     ('Nie mam żadnych dzieci.', 'Eu não tenho filhos.'), ('Jak się masz?', 'Como vai você?'),
     ('Jak leci?', 'Como vai você?'), ('Jak się mają?', 'Como eles estão?'),
     ('Dzięki bardzo dobrze a ty?', 'Obrigado muito bem e você?'), ('Dobrze, dzięki.', 'Bom obrigado.'),
     ('Świetnie!', 'Ótimo!'), ('Tak sobie.', 'Nada bom.'), ('Nieźle, dzięki.', 'Nada mal, obrigado.'),
     ('Mogło być gorzej.', 'Poderia ser pior.'), ('Nic mi nie jest.', 'Estou bem.'),
     ('Jestem zmęczony.', 'Estou cansado.'), ('Durst.', 'Durst.'), ('Gdzie pracujesz?', 'Onde você trabalha?'),
     ('Co robisz?', 'O que você está fazendo?'), ('Czym się zajmujesz?', 'O que você faz?'),
     ('Jestem samozatrudniony.', 'Eu trabalho por conta própria.'), ('Jestem bezrobotny.', 'Eu estou desempregado.'),
     ('Jestem na uniwersytecie.', 'Estou na universidade.'), ('Jestem na emeryturze.', 'Estou aposentado.'),
     ('Ja podróżuję.', 'Estou viajando.'), ('Pracuję w domu.', 'Eu trabalho em casa.'), ('Jest dziewiąta.', 'É nono.'),
     ('To dziesięć w ciągu dziewięciu.', 'São dez em nove.'),
     ('Jest piętnaście po dziewiątej.', 'São quinze depois das nove.'),
     ('Jest 25 mini dziewiątych.', 'Há 25 mini nove.'), ('Jest w pół do dziesiątej.', 'É da metade a dez.'),
     ('To 20 do dziesięciu.', 'São 20 a dez.'), ('To kwartał do dziesięciu.', 'Este é um quarto a dez.'),
     ('To pięć do dziesięciu.', 'São de cinco a dez.'), ('Jest 17:30.', 'São 17:30.'), ('Gdy?', 'Quando?'),
     ('Jaka jest pogoda?', 'Como está o tempo?'), ('Będzie padać?', 'Vai chover?'),
     ('Co za piękny dzień!', 'Que dia lindo!'), ('Jaka okropna pogoda!', 'Quão terrível clima!'),
     ('Jest słonecznie.', 'Está ensolarado.'), ('Jest mgliście.', 'Está nublado.'), ('Jest lodowato.', 'É gelado.'),
     ('Jest wietrznie.', 'Está ventando.'), ('Jest burzowo.', 'É tempestuoso.'), ('Jest zmienny.', 'É variável.')])
